name: Deploying to VPS

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch: # This allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Build
        run: |
          npm install
          DISABLE_ESLINT_PLUGIN=true npm run build

      - name: Delete .map
        run: find ./build/ -type f -name "*.map" -exec rm -f {} \;

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ vars.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          rsync -av ./build/ ${{ vars.VPS_USERNAME }}@${{ vars.VPS_IP }}:${{ vars.DEPLOY_PATH }}

        env:
          SSH_AUTH_SOCK: /tmp/ssh-agent.sock
